podTemplate(
  label: "skopeo-pod",
  cloud: "openshift",
  inheritFrom: "maven",
  containers: [
    containerTemplate(
      name: "jnlp",
      image: "docker-registry.default.svc:5000/7115-jenkins/jenkins-agent-appdev",
      resourceRequestMemory: "1Gi",
      resourceLimitMemory: "2Gi",
      resourceRequestCpu: "1",
      resourceLimitCpu: "2"
    )
  ]
) {
  def prefix      = "7115"
  def mvnCmd      = "mvn -s ../nexus_settings.xml"
  def devProject  = "${prefix}-tasks-dev"
  def prodProject = "${prefix}-tasks-prod"
  def devTag      = "0.0-0"
  def prodTag     = "0.0"
  def destApp     = "tasks-green"
  def activeApp   = ""

  node('skopeo-pod') {

    stage('Checkout Source') {
      checkout scm
    }

    dir('openshift-tasks') {
      def version = getVersionFromPom("pom.xml")
      echo "Building version ${version}"
      devTag  = "${version}-" + currentBuild.number
      echo "Building devTag ${devTag}"
      prodTag = "${version}"
      echo "Building prodTag ${prodTag}"

      stage('Build war') {
        echo "Building version ${devTag}"
        sh "${mvnCmd} clean package -DskipTests=true"
      }

      stage('Parallel Tasks') {
        echo "Starting Parallel Tasks"
        openshift.withCluster() {
          openshift.withProject() {
            parallel {
              stage('Unit Tests') {
                echo "Running Unit Tests"
                sh "${mvnCmd} test"
              }
              stage('Code Analysis') {
                echo "Running Code Analysis"
                sh "${mvnCmd} sonar:sonar -Dsonar.host.url=http://sonarqube.gpte-hw-cicd.svc.cluster.local:9000 -DskipTests"
              }
            }
          }
        }
      }

      // Publish the built war file to Nexus
      stage('Publish to Nexus') {
        sh "${mvnCmd} deploy -DskipTests=true -DaltDeploymentRepository=nexus::default::http://nexus3-gpte-hw-cicd.apps.na311.openshift.opentlc.com/repository/releases"
      }

      // Build the OpenShift Image in OpenShift and tag it.
      stage('Build and Tag OpenShift Image') {
        echo "Building OpenShift container image tasks:${devTag}"
        script {
          openshift.withCluster() {
            openshift.withProject("${devProject}") {
              openshift.selector("bc", "tasks").startBuild("--from-file=./target/openshift-tasks.war", "--wait=true")
              openshift.tag("tasks:latest", "tasks:${devTag}")
            }
          }
        }
      }

      // Deploy the built image to the Development Environment.
      stage('Deploy to Dev') {
        echo "Deploying container image to Development Project"

        // TBD: Deploy to development Project
        //      Set Image, Set VERSION
        //      Make sure the application is running and ready before proceeding
      }

      // Copy Image to Nexus container registry
      stage('Copy Image to Nexus container registry') {
        echo "Copy image to Nexus container registry"

        // TBD: Copy image to Nexus container registry

        // TBD: Tag the built image with the production tag.
      }

      // Blue/Green Deployment into Production
      // -------------------------------------
      //def destApp   = "tasks-green"
      //def activeApp = ""

      stage('Blue/Green Production Deployment') {
        // TBD: Determine which application is active
        //      Set Image, Set VERSION
        //      Deploy into the other application
        //      Make sure the application is running and ready before proceeding
      }

      stage('Switch over to new Version') {
        echo "Switching Production application to ${destApp}."
        // TBD: Execute switch
      }
    }
  }

}

// Convenience Functions to read version from the pom.xml
// Do not change anything below this line.
// --------------------------------------------------------
def getVersionFromPom(pom) {
  def matcher = readFile(pom) =~ '<version>(.+)</version>'
  matcher ? matcher[0][1] : null
}
